spring.application.name=order-service
server.port=8080
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.info.env.enabled=true
info.app.name=order-service
info.app.version=1.0.0
